# Generated by Django 5.2.6 on 2025-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes', '0002_customer_alter_product_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('nylon_tubes', 'Nylon Tubes'), ('hoses', 'Hoses'), ('assemblies', 'Assemblies')], max_length=20),
        ),
    ]
