# Generated by Django 5.2.7 on 2026-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes', '0005_category_alter_product_options_product_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('nylon_tubes', 'Nylon Tubes'), ('hoses', 'Hoses'), ('assemblies', 'Assemblies')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
