# Generated by Django 5.2.7 on 2026-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes', '0011_quotationrequest_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='products',
            field=models.TextField(blank=True),
        ),
    ]
