# Generated by Django 5.2.7 on 2026-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes', '0014_partrequest_delete_productrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_company', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.CharField(blank=True, max_length=10)),
                ('part_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='requested_products/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PartRequest',
        ),
    ]
